export const heroSearchExamples = [
  "Financial Accounting",
  "Microeconomics",
  "Linear Algebra",
  "Corporate Finance",
  "Data Structures",
];

export const skillMoments = [
  {
    studentId: "camille-martin",
    name: "Camille M.",
    service: "Financial Accounting",
    area: "ESCP / 17e",
    availability: "Available tonight",
    price: "€28/hour",
    travel: "Professor Dupont",
    university: "ESCP Business School",
  },
  {
    studentId: "youssef-benali",
    name: "Youssef B.",
    service: "Microeconomics",
    area: "Dauphine / 16e",
    availability: "Online tomorrow",
    price: "€24/hour",
    travel: "Professor Martin",
    university: "Université Paris Dauphine - PSL",
  },
  {
    studentId: "lea-moreau",
    name: "Léa M.",
    service: "Linear Algebra",
    area: "Sorbonne / 5e",
    availability: "Friday 14:00",
    price: "€26/hour",
    travel: "Professor Moreau",
    university: "Sorbonne Université",
  },
  {
    studentId: "marc-vidal",
    name: "Marc V.",
    service: "European Law",
    area: "Sciences Po / 7e",
    availability: "Monday 16:00",
    price: "€27/hour",
    travel: "Professor Garnier",
    university: "Sciences Po Paris",
  },
];

export const parisMotionMoments = [
  {
    time: "08:30",
    task: "ESCP Financial Accounting",
    area: "17e",
    areaNumber: 17,
    studentId: "camille-martin",
    preview: "Three verified mentors around ESCP know Professor Dupont's accounting cases.",
    detail: "Campus-area availability",
    center: [2.3068, 48.8873] as [number, number],
    zoom: 12.7,
  },
  {
    time: "13:00",
    task: "Dauphine Microeconomics",
    area: "16e",
    areaNumber: 16,
    studentId: "youssef-benali",
    preview: "Compare mentors who already completed the same Dauphine problem sets.",
    detail: "Online or campus study session",
    center: [2.2744, 48.8718] as [number, number],
    zoom: 12.9,
  },
  {
    time: "17:30",
    task: "Sorbonne Mathematics",
    area: "5e",
    areaNumber: 5,
    studentId: "lea-moreau",
    preview: "Find mentors for linear algebra, proof structure, and exam preparation.",
    detail: "Safe meeting areas near campus",
    center: [2.345, 48.8462] as [number, number],
    zoom: 13,
  },
  {
    time: "20:00",
    task: "Sciences Po European Law",
    area: "7e",
    areaNumber: 7,
    studentId: "marc-vidal",
    preview: "Book law mentoring around essay structure, case law, and seminar preparation.",
    detail: "Arrondissement-level mentor area",
    center: [2.3187, 48.8556] as [number, number],
    zoom: 13.1,
  },
];

export const pulseItems = [
  "Camille opened two Financial Accounting slots near ESCP.",
  "A new Corporate Finance case-note pack was added today.",
  "Youssef is available online for Microeconomics tomorrow.",
  "Léa added Linear Algebra problem sheet notes.",
  "Marc can review European Law essay plans this week.",
];
